"""Adapter helpers."""

from vptune.adapters.distributed import (
    DistributedAdmissionPolicy,
    RankCompileTiming,
    RankSelectedSettings,
    RankStatus,
    admit_distributed_candidate,
    apply_context_parallel,
    apply_fsdp2,
    apply_fsdp2_group,
    apply_tensor_parallel,
    build_colwise_parallel,
    build_device_mesh,
    build_dtensor_placement,
    build_fsdp_dp_mesh_dims,
    build_fsdp_mixed_precision_policy,
    build_fsdp_offload_policy,
    build_prepare_module_input,
    build_prepare_module_output,
    build_rowwise_parallel,
    build_sequence_parallel,
    collective_all_gather_into_tensor,
    collective_all_to_all_single,
    collective_reduce_scatter_tensor,
    distributed_identity,
    distributed_record,
    distributed_strategy_axis,
    initialize_process_group,
    named_modules_for_distributed_wrap,
    redistribute_dtensor,
    reduce_rank_statuses,
    require_rank_selected_settings_agree,
    resolve_process_group_backend,
    run_with_loss_parallel,
    wait_collective,
)
from vptune.adapters.pilot import (
    PILOT_ACCEPTANCE_FAMILIES,
    PilotReadiness,
)
from vptune.adapters.pilot import (
    acceptance_family_names as pilot_acceptance_family_names,
)
from vptune.adapters.pilot import (
    acceptance_readiness as pilot_acceptance_readiness,
)
from vptune.adapters.pilot import (
    lower as pilot_lower,
)
from vptune.adapters.pilot import (
    readiness as pilot_readiness,
)
from vptune.adapters.pilot import (
    require_acceptance_families as pilot_require_acceptance_families,
)
from vptune.adapters.pilot import (
    selected_settings as pilot_selected_settings,
)
from vptune.adapters.pilot import (
    validators as pilot_validators,
)
from vptune.adapters.transformers import (
    TransformersAttentionPolicy,
    TransformersModelIdentity,
    admit_transformers_attention,
    admit_transformers_cache,
    load_transformers_model,
    register_transformers_attention,
    set_transformers_attention_implementation,
    transformers_attention_axis,
    transformers_attention_location,
    transformers_attn_implementation,
    transformers_cache_axis,
    transformers_model_identity,
)

__all__ = [
    "PILOT_ACCEPTANCE_FAMILIES",
    "DistributedAdmissionPolicy",
    "PilotReadiness",
    "RankCompileTiming",
    "RankSelectedSettings",
    "RankStatus",
    "TransformersAttentionPolicy",
    "TransformersModelIdentity",
    "admit_distributed_candidate",
    "admit_transformers_attention",
    "admit_transformers_cache",
    "apply_context_parallel",
    "apply_fsdp2",
    "apply_fsdp2_group",
    "apply_tensor_parallel",
    "build_colwise_parallel",
    "build_device_mesh",
    "build_dtensor_placement",
    "build_fsdp_dp_mesh_dims",
    "build_fsdp_mixed_precision_policy",
    "build_fsdp_offload_policy",
    "build_prepare_module_input",
    "build_prepare_module_output",
    "build_rowwise_parallel",
    "build_sequence_parallel",
    "collective_all_gather_into_tensor",
    "collective_all_to_all_single",
    "collective_reduce_scatter_tensor",
    "distributed_identity",
    "distributed_record",
    "distributed_strategy_axis",
    "initialize_process_group",
    "load_transformers_model",
    "named_modules_for_distributed_wrap",
    "pilot_acceptance_family_names",
    "pilot_acceptance_readiness",
    "pilot_lower",
    "pilot_readiness",
    "pilot_require_acceptance_families",
    "pilot_selected_settings",
    "pilot_validators",
    "redistribute_dtensor",
    "reduce_rank_statuses",
    "register_transformers_attention",
    "require_rank_selected_settings_agree",
    "resolve_process_group_backend",
    "run_with_loss_parallel",
    "set_transformers_attention_implementation",
    "transformers_attention_axis",
    "transformers_attention_location",
    "transformers_attn_implementation",
    "transformers_cache_axis",
    "transformers_model_identity",
    "wait_collective",
]
